### ISSUE TITLE
Add List/Iterate Devices Example

### ISSUE THREAD

**Issue by sankarsubramanian** [attm2x/m2x-php#27]
Iterate Over List of Devices: this example should List Devices and then show how to iterate over the paginated list of devices that is returned by the API.

Here's a similar example in Python:
https://github.com/attm2x/m2x-python/blob/master/examples/iterate_over_devices.py

**Comment by majidabdul** [comment]
@kristinpeterson https://github.com/attm2x/m2x-php/pull/28 has resolved this issue.
