### ISSUE TITLE
installation over online server

### ISSUE THREAD

**Issue by savyad** [attm2x/m2x-php#35]
How to install m2x-php over my godaddy online server.It's not making any sense to me pls help

**Comment by sarahhenkens** [comment]
Hi @savyad can you provide me with some more information about your server? Do you have SSH access to your own dedicated server or do you only have cpanel available to you?

**Comment by savyad** [comment]
Yes i have got access to ssh on my server

**Comment by sarahhenkens** [comment]
The simplest way to install the `m2x-php` package is leveraging the [composer](https://getcomposer.org) package manager.

Documentation on how to setup your project to use composer can be found here:
https://getcomposer.org/doc/00-intro.md

A bare-bones example composer file:
```json
{
    "name": "vendor-name/project-name",
    "description": "This is a very cool package!",
    "version": "0.0.1",
    "require": {
        "attm2x/m2x-php": "~4.0"
    }
}
```

And after you run `php composer.phar install` the m2x library should be available in your project. 

#### Getting the code in your own application code

The M2X package defines autoload information. By including composer's autoload vendor file, the package will become available in your project. More info can be found on https://getcomposer.org/doc/01-basic-usage.md#autoloading

Let me know if you have any more questions!

**Comment by savyad** [comment]
Thanks for helping but i already figured that out,since you asked would you
please tell me from where should i start developing because,the thing is i
got a device which transmits the data and i am receiving the data on my
server and i want that data to be pushed over m2x cloud to make charts and
graphs.

**Comment by savyad** [comment]
and also while running the "uptime.php" i specified my apikey and device id
still there is nothing on the dashboard.I have not created any streams
because you say so in the tutorial.pls help

**Comment by savyad** [comment]
following is the log file generated please take a look

[15-Feb-2018 06:59:06 UTC] PHP Fatal error:  Uncaught Att\M2X\Error\M2XException in /home/miigo2017/public_html/vendor/attm2x/m2x-php/src/M2X.php:395
Stack trace:
#0 /home/miigo2017/public_html/vendor/attm2x/m2x-php/src/M2X.php(317): Att\M2X\M2X->handleResponse(Object(Att\M2X\HttpResponse))
#1 /home/miigo2017/public_html/vendor/attm2x/m2x-php/src/Resource.php(71): Att\M2X\M2X->get('/devices/')
#2 /home/miigo2017/public_html/vendor/attm2x/m2x-php/src/M2X.php(211): Att\M2X\Resource::get(Object(Att\M2X\M2X), false)
#3 /home/miigo2017/public_html/data.php(12): Att\M2X\M2X->device(false)
#4 {main}
  thrown in /home/miigo2017/public_html/vendor/attm2x/m2x-php/src/M2X.php on line 395

**Comment by sarahhenkens** [comment]
@savyad Is that stack trace from running the uptime.php example?
